### PR TITLE
Migrate APIs.guru URL to specs

### PR DESCRIPTION
**Pull request by IvanGoncharov**
More details here: https://github.com/APIs-guru/api-models/issues/85

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@darosh Can you please review it?
It blocks migration to V2.

**Comment by IvanGoncharov** [comment]
@darosh Changes are very simple, please review them.

**Comment by IvanGoncharov** [comment]
@darosh Can you please review this change?

**Comment by darosh** [comment]
@IvanGoncharov thanks!

**Comment by IvanGoncharov** [comment]
👍

**Pull request merged**
